[build]
  publish = "."

[[headers]]
  for = "/public/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/privacy"
  to = "/"
  status = 302

[[redirects]]
  from = "/terms"
  to = "/"
  status = 302
